-- 香調アコードマスタ・香料マスタのシード
--
-- このファイルは tools/ingestion が生成する。直接編集しないこと。
--   cd tools/ingestion && python -m ingestion.build_masters && python -m ingestion.emit_seed
--
-- 香調アコード 21 件 / 香料 497 件 / 別名 1195 件
-- 出所と生成手順は docs/data-ingestion.md を参照。

insert into accords (slug, name_en, name_ja, sort_order) values
  ('floral', 'Floral', 'フローラル', 0),
  ('spicy', 'Spicy', 'スパイシー', 1),
  ('sweet', 'Sweet', 'スイート', 2),
  ('woody', 'Woody', 'ウッディ', 3),
  ('fresh', 'Fresh', 'フレッシュ', 4),
  ('fruity', 'Fruity', 'フルーティ', 5),
  ('citrus', 'Citrus', 'シトラス', 6),
  ('green', 'Green', 'グリーン', 7),
  ('powdery', 'Powdery', 'パウダリー', 8),
  ('synthetic', 'Synthetic', 'シンセティック', 9),
  ('oriental', 'Oriental', 'オリエンタル', 10),
  ('creamy', 'Creamy', 'クリーミー', 11),
  ('gourmand', 'Gourmand', 'グルマン', 12),
  ('resinous', 'Resinous', 'レジナス', 13),
  ('aquatic', 'Aquatic', 'アクアティック', 14),
  ('smoky', 'Smoky', 'スモーキー', 15),
  ('leathery', 'Leathery', 'レザリー', 16),
  ('earthy', 'Earthy', 'アーシー', 17),
  ('animal', 'Animal', 'アニマリック', 18),
  ('chypre', 'Chypre', 'シプレ', 19),
  ('fougere', 'Fougère', 'フゼア', 20)
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_ja = excluded.name_ja,
  sort_order = excluded.sort_order;

insert into notes (slug, name_en, name_ja, family, needs_review) values
  ('musk', 'musk', 'ムスク', 'musk', false),
  ('bergamot', 'bergamot', 'ベルガモット', 'citrus', false),
  ('sandalwood', 'sandalwood', 'サンダルウッド', 'woody', false),
  ('jasmine', 'jasmine', 'ジャスミン', 'white_floral', false),
  ('rose', 'rose', 'ローズ', 'floral', false),
  ('vanilla', 'vanilla', 'バニラ', 'gourmand', false),
  ('amber', 'amber', 'アンバー', 'balsamic', false),
  ('patchouli', 'patchouli', 'パチュリ', 'woody', false),
  ('cedarwood', 'cedarwood', 'シダーウッド', 'woody', false),
  ('mandarin-orange', 'mandarin orange', 'マンダリンオレンジ', 'citrus', false),
  ('vetiver', 'vetiver', 'ベチバー', 'woody', false),
  ('lemon', 'lemon', 'レモン', 'citrus', false),
  ('iris', 'iris', 'イリス', 'floral', false),
  ('tonka-bean', 'tonka bean', 'トンカビーン', 'gourmand', false),
  ('oakmoss', 'oakmoss', 'オークモス', 'earthy', false),
  ('lavender', 'lavender', 'ラベンダー', 'floral', false),
  ('orange-blossom', 'orange blossom', 'オレンジブロッサム', 'white_floral', false),
  ('lily-of-the-valley', 'lily of the valley', 'スズラン', 'white_floral', false),
  ('grapefruit', 'grapefruit', 'グレープフルーツ', 'citrus', false),
  ('ylang-ylang', 'ylang-ylang', 'イランイラン', 'white_floral', false),
  ('cardamom', 'cardamom', 'カルダモン', 'spicy', false),
  ('geranium', 'geranium', 'ゼラニウム', 'floral', false),
  ('oud', 'oud', 'ウード', 'woody', false),
  ('violet', 'violet', 'バイオレット', 'floral', false),
  ('pink-pepper', 'pink pepper', 'ピンクペッパー', 'spicy', false),
  ('frankincense', 'frankincense', 'フランキンセンス', 'balsamic', false),
  ('benzoin', 'benzoin', 'ベンゾイン', 'balsamic', false),
  ('leather', 'leather', 'レザー', 'leather', false),
  ('white-musk', 'white musk', 'ホワイトムスク', 'musk', false),
  ('orange', 'orange', 'オレンジ', 'citrus', false),
  ('peach', 'peach', '桃', 'fruity', false),
  ('blackcurrant', 'blackcurrant', 'カシス', 'fruity', false),
  ('cinnamon', 'cinnamon', 'シナモン', 'spicy', false),
  ('neroli', 'neroli', 'ネロリ', 'citrus', false),
  ('ambergris', 'ambergris', 'アンバーグリス', 'animalic', false),
  ('freesia', 'freesia', 'フリージア', 'white_floral', false),
  ('nutmeg', 'nutmeg', 'ナツメグ', 'spicy', false),
  ('saffron', 'saffron', 'サフラン', 'spicy', false),
  ('tuberose', 'tuberose', 'チュベローズ', 'white_floral', false),
  ('ginger', 'ginger', 'ジンジャー', 'spicy', false),
  ('labdanum', 'labdanum', 'ラブダナム', 'balsamic', false),
  ('apple', 'apple', '林檎', 'fruity', false),
  ('raspberry', 'raspberry', 'ラズベリー', 'fruity', false),
  ('peony', 'peony', 'ピオニー', 'floral', false),
  ('woody-notes', 'woody notes', 'ウッディノート', 'woody', false),
  ('heliotrope', 'heliotrope', 'ヘリオトロープ', 'floral', false),
  ('coriander', 'coriander', 'コリアンダー', 'spicy', false),
  ('pear', 'pear', '洋梨', 'fruity', false),
  ('clove', 'clove', 'クローブ', 'spicy', false),
  ('cashmeran', 'cashmeran', 'カシュメラン', 'woody', false),
  ('magnolia', 'magnolia', 'マグノリア', 'white_floral', false),
  ('black-pepper', 'black pepper', 'ブラックペッパー', 'spicy', false),
  ('carnation', 'carnation', 'カーネーション', 'floral', false),
  ('pepper', 'pepper', 'ペッパー', 'spicy', false),
  ('gardenia', 'gardenia', 'ガーデニア', 'white_floral', false),
  ('aquatic', 'aquatic', 'アクアティック', 'aquatic', false),
  ('green-notes', 'green notes', 'グリーンノート', 'green', false),
  ('violet-leaf', 'violet leaf', 'バイオレットリーフ', 'green', false),
  ('gaiac-wood', 'gaiac wood', 'ガイアックウッド', 'woody', false),
  ('plum', 'plum', 'プラム', 'fruity', false),
  ('aldehydes', 'aldehydes', 'アルデヒド', 'aldehydic', false),
  ('lime', 'lime', 'ライム', 'citrus', false),
  ('mint', 'mint', 'ミント', 'herbal', false),
  ('pineapple', 'pineapple', 'パイナップル', 'fruity', false),
  ('rosemary', 'rosemary', 'ローズマリー', 'herbal', false),
  ('basil', 'basil', 'バジル', 'herbal', false),
  ('juniper', 'juniper', 'ジュニパー', 'woody', false),
  ('jasmine-sambac', 'jasmine sambac', 'サンバックジャスミン', 'white_floral', false),
  ('galbanum', 'galbanum', 'ガルバナム', 'green', false),
  ('sage', 'sage', 'セージ', 'herbal', false),
  ('tobacco', 'tobacco', 'タバコ', 'tobacco', false),
  ('petitgrain', 'petitgrain', 'プチグレン', 'citrus', false),
  ('clary-sage', 'clary sage', 'クラリセージ', 'herbal', false),
  ('lily', 'lily', 'リリー', 'white_floral', false),
  ('rosewood', 'rosewood', 'ローズウッド', 'woody', false),
  ('honey', 'honey', '蜂蜜', 'gourmand', false),
  ('myrrh', 'myrrh', 'ミルラ', 'balsamic', false),
  ('orchid', 'orchid', 'オーキッド', 'white_floral', false),
  ('caramel', 'caramel', 'キャラメル', 'gourmand', false),
  ('osmanthus', 'osmanthus', '金木犀', 'other', false),
  ('cypress', 'cypress', 'サイプレス', 'woody', false),
  ('spices', 'spices', 'スパイス', 'spicy', false),
  ('cyclamen', 'cyclamen', 'シクラメン', 'floral', false),
  ('ambroxan', 'ambroxan', 'アンブロキサン', 'synthetic', false),
  ('coconut', 'coconut', 'ココナッツ', 'fruity', false),
  ('mimosa', 'mimosa', 'ミモザ', 'floral', false),
  ('elemi', 'elemi', 'エレミ', 'spicy', false),
  ('hyacinth', 'hyacinth', 'ヒヤシンス', 'floral', false),
  ('lychee', 'lychee', 'ライチ', 'fruity', false),
  ('may-rose', 'may rose', 'メイローズ', 'floral', false),
  ('lotus', 'lotus', 'ロータス', 'floral', false),
  ('bitter-orange', 'bitter orange', 'ビターオレンジ', 'citrus', false),
  ('civet', 'civet', 'シベット', 'animalic', false),
  ('cistus', 'cistus', 'シスタス', 'other', false),
  ('apricot', 'apricot', 'アプリコット', 'fruity', false),
  ('almond', 'almond', 'アーモンド', 'gourmand', false),
  ('narcissus', 'narcissus', 'ナルシス', 'floral', false),
  ('wormwood', 'wormwood', 'ニガヨモギ', 'herbal', false),
  ('honeysuckle', 'honeysuckle', 'スイカズラ', 'white_floral', false),
  ('thyme', 'thyme', 'タイム', 'herbal', false),
  ('green-apple', 'green apple', '青林檎', 'fruity', false),
  ('melon', 'melon', 'メロン', 'fruity', false),
  ('lilac', 'lilac', 'ライラック', 'other', false),
  ('praline', 'praliné', 'プラリネ', 'other', false),
  ('strawberry', 'strawberry', '苺', 'fruity', false),
  ('coffee', 'coffee', 'コーヒー', 'gourmand', false),
  ('anise', 'anise', 'アニス', 'spicy', false),
  ('frangipani', 'frangipani', 'プルメリア', 'white_floral', false),
  ('passion-fruit', 'passion fruit', 'パッションフルーツ', 'fruity', false),
  ('suede', 'suede', 'スエード', 'leather', false),
  ('tarragon', 'tarragon', 'タラゴン', 'herbal', false),
  ('cocoa', 'cocoa', 'カカオ', 'gourmand', false),
  ('rhubarb', 'rhubarb', 'ルバーブ', 'fruity', false),
  ('yuzu', 'yuzu', '柚子', 'citrus', false),
  ('blackberry', 'blackberry', 'ブラックベリー', 'fruity', false),
  ('cumin', 'cumin', 'クミン', 'spicy', false),
  ('green-tea', 'green tea', '緑茶', 'tea', false),
  ('rum', 'rum', 'ラム', 'boozy', false),
  ('cypriol', 'cypriol', 'サイプリオール', 'woody', false),
  ('star-anise', 'star anise', '八角', 'spicy', false),
  ('fig', 'fig', 'イチジク', 'fruity', false),
  ('opoponax', 'opoponax', 'オポポナックス', 'balsamic', false),
  ('verbena', 'verbena', 'バーベナ', 'herbal', false),
  ('blood-orange', 'blood orange', 'ブラッドオレンジ', 'citrus', false),
  ('birch', 'birch', 'バーチ', 'woody', false),
  ('water-lily', 'water lily', 'スイレン', 'floral', false),
  ('mango', 'mango', 'マンゴー', 'fruity', false),
  ('davana', 'davana', 'ダバナ', 'other', false),
  ('tea', 'tea', '紅茶', 'tea', false),
  ('ozonic', 'ozonic', 'オゾンノート', 'aquatic', false),
  ('castoreum', 'castoreum', 'カストリウム', 'animalic', false),
  ('ambrette-seed', 'ambrette seed', 'アンブレットシード', 'other', false),
  ('watermelon', 'watermelon', 'スイカ', 'fruity', false),
  ('pine', 'pine', 'パイン', 'woody', false),
  ('tolu-balsam', 'tolu balsam', 'トルーバルサム', 'balsamic', false),
  ('pimento', 'pimento', 'ピメント', 'spicy', false),
  ('red-fruits', 'red fruits', '赤い果実', 'fruity', false),
  ('tiare', 'tiaré', 'ティアレ', 'other', false),
  ('tagetes', 'tagetes', 'マリーゴールド', 'other', false),
  ('cherry', 'cherry', 'チェリー', 'fruity', false),
  ('white-cedar', 'white cedar', 'ホワイトシダー', 'woody', false),
  ('angelica', 'angelica', 'アンジェリカ', 'herbal', false),
  ('chamomile', 'chamomile', 'カモミール', 'floral', false),
  ('caraway', 'caraway', 'キャラウェイ', 'spicy', false),
  ('fir-balsam', 'fir balsam', 'モミの樹脂', 'balsamic', false),
  ('pomegranate', 'pomegranate', 'ザクロ', 'fruity', false),
  ('peppermint', 'peppermint', 'ペパーミント', 'herbal', false),
  ('citron', 'citron', 'シトロン', 'citrus', false),
  ('peru-balsam', 'peru balsam', 'ペルーバルサム', 'balsamic', false),
  ('fig-leaf', 'fig leaf', 'フィグリーフ', 'green', false),
  ('ambrette', 'ambrette', 'アンブレット', 'musk', false),
  ('blackcurrant-bud', 'blackcurrant bud', 'カシスの芽', 'green', false),
  ('white-pepper', 'white pepper', 'ホワイトペッパー', 'spicy', false),
  ('eucalyptus', 'eucalyptus', 'ユーカリ', 'herbal', false),
  ('chocolate', 'chocolate', 'チョコレート', 'gourmand', false),
  ('sea-salt', 'sea salt', '海塩', 'aquatic', false),
  ('cherry-blossom', 'cherry blossom', '桜', 'floral', false),
  ('immortelle', 'immortelle', 'イモーテル', 'floral', false),
  ('powdery-notes', 'powdery notes', 'パウダリーノート', 'powdery', false),
  ('oak', 'oak', 'オーク', 'other', false),
  ('papyrus', 'papyrus', 'パピルス', 'woody', false),
  ('amyris', 'amyris', 'アミリス', 'woody', false),
  ('milk', 'milk', 'ミルク', 'gourmand', false),
  ('red-apple', 'red apple', '赤林檎', 'fruity', false),
  ('mate', 'maté', null, 'tea', false),
  ('mugwort', 'mugwort', 'ヨモギ', 'herbal', false),
  ('nectarine', 'nectarine', 'ネクタリン', 'fruity', false),
  ('licorice', 'licorice', 'リコリス', 'gourmand', false),
  ('berries', 'berries', 'ベリー', 'fruity', false),
  ('coumarin', 'coumarin', 'クマリン', 'aromatic', false),
  ('driftwood', 'driftwood', '流木', 'woody', false),
  ('teak', 'teak', 'チーク', 'woody', false),
  ('grass', 'grass', '草', 'green', false),
  ('sichuan-pepper', 'sichuan pepper', '花椒', 'spicy', false),
  ('blossoms', 'blossoms', '花々', 'floral', false),
  ('white-rose', 'white rose', '白薔薇', 'floral', false),
  ('black-tea', 'black tea', '紅茶', 'tea', false),
  ('bamboo', 'bamboo', '竹', 'green', false),
  ('sugar', 'sugar', '砂糖', 'gourmand', false),
  ('apple-blossom', 'apple blossom', '林檎の花', 'floral', false),
  ('resins', 'resins', '樹脂', 'balsamic', false),
  ('fresh-notes', 'fresh notes', 'フレッシュノート', 'other', false),
  ('peach-blossom', 'peach blossom', '桃の花', 'floral', false),
  ('chili', 'chili', 'チリ', 'spicy', false),
  ('hawthorn', 'hawthorn', 'サンザシ', 'other', false),
  ('myrtle', 'myrtle', 'ミルテ', 'herbal', false),
  ('laurel', 'laurel', 'ローレル', 'herbal', false),
  ('red-currant', 'red currant', '赤スグリ', 'fruity', false),
  ('hay', 'hay', '干し草', 'green', false),
  ('coconut-milk', 'coconut milk', 'ココナッツミルク', 'fruity', false),
  ('spearmint', 'spearmint', 'スペアミント', 'herbal', false),
  ('balsamic-notes', 'balsamic notes', 'バルサミックノート', 'balsamic', false),
  ('beeswax', 'beeswax', '蜜蝋', 'balsamic', false),
  ('treemoss', 'treemoss', 'ツリーモス', 'earthy', false),
  ('nagarmotha', 'nagarmotha', 'ナガルモタ', 'woody', false),
  ('aromatic-notes', 'aromatic notes', 'アロマティックノート', 'aromatic', false),
  ('hibiscus', 'hibiscus', 'ハイビスカス', 'floral', false),
  ('ivy', 'ivy', 'アイビー', 'green', false),
  ('sweet-notes', 'sweet notes', 'スイートノート', 'other', false),
  ('mastic', 'mastic', 'マスティック', 'balsamic', false),
  ('cedar-leaf', 'cedar leaf', 'シダーリーフ', 'woody', false),
  ('fruits', 'fruits', '果実', 'fruity', false),
  ('hazelnut', 'hazelnut', 'ヘーゼルナッツ', 'gourmand', false),
  ('dry-woods', 'dry woods', 'ドライウッド', 'woody', false),
  ('hedione', 'hedione', 'ヘディオン', 'synthetic', false),
  ('animalic-notes', 'animalic notes', 'アニマリックノート', 'animalic', false),
  ('waterlily', 'waterlily', 'スイレン', 'floral', false),
  ('white-woods', 'white woods', 'ホワイトウッド', 'woody', false),
  ('mahogany', 'mahogany', 'マホガニー', 'woody', false),
  ('white-tea', 'white tea', '白茶', 'tea', false),
  ('blueberry', 'blueberry', 'ブルーベリー', 'fruity', false),
  ('smoke', 'smoke', '煙', 'tobacco', true),
  ('gurjun-balsam', 'gurjun balsam', 'ガジュツバルサム', 'balsamic', false),
  ('bay-leaf', 'bay leaf', 'ローリエ', 'herbal', false),
  ('kumquat', 'kumquat', '金柑', 'citrus', false),
  ('pine-needle', 'pine needle', '松葉', 'woody', false),
  ('ebony', 'ebony', '黒檀', 'woody', false),
  ('lemon-zest', 'lemon zest', 'レモンの皮', 'citrus', false),
  ('fir', 'fir', 'モミ', 'woody', false),
  ('cassia', 'cassia', 'カッシア', 'spicy', false),
  ('currant', 'currant', 'スグリ', 'fruity', false),
  ('white-lily', 'white lily', '白百合', 'white_floral', false),
  ('marshmallow', 'marshmallow', 'マシュマロ', 'gourmand', false),
  ('cucumber', 'cucumber', 'キュウリ', 'green', false),
  ('bitter-almond', 'bitter almond', 'ビターアーモンド', 'gourmand', false),
  ('coconut-water', 'coconut water', 'ココナッツウォーター', 'fruity', false),
  ('dried-fruits', 'dried fruits', 'ドライフルーツ', 'fruity', false),
  ('kiwi', 'kiwi', 'キウイ', 'fruity', false),
  ('guava', 'guava', 'グアバ', 'fruity', false),
  ('white-peony', 'white peony', '白牡丹', 'floral', false),
  ('balsam', 'balsam', 'バルサム', 'balsamic', false),
  ('carrot-seed', 'carrot seed', 'キャロットシード', 'spicy', false),
  ('herbs', 'herbs', 'ハーブ', 'herbal', false),
  ('dark-chocolate', 'dark chocolate', 'ダークチョコレート', 'gourmand', false),
  ('broom', 'broom', 'エニシダ', 'other', false),
  ('pink-peony', 'pink peony', 'ピンクピオニー', 'floral', false),
  ('fern', 'fern', 'シダ', 'green', false),
  ('coriander-seed', 'coriander seed', 'コリアンダーシード', 'spicy', false),
  ('almond-blossom', 'almond blossom', 'アーモンドの花', 'floral', false),
  ('lemon-grass', 'lemon grass', 'レモングラス', 'citrus', false),
  ('seawater', 'seawater', '海水', 'aquatic', false),
  ('cream', 'cream', 'クリーム', 'gourmand', false),
  ('cranberry', 'cranberry', 'クランベリー', 'fruity', false),
  ('papaya', 'papaya', 'パパイヤ', 'fruity', false),
  ('quince', 'quince', 'マルメロ', 'fruity', false),
  ('wisteria', 'wisteria', '藤', 'floral', false),
  ('nashi-pear', 'nashi pear', '梨', 'fruity', false),
  ('champaca', 'champaca', 'チャンパカ', 'white_floral', false),
  ('diesel', 'diesel', 'ディーゼル', 'other', true),
  ('marigold', 'marigold', 'マリーゴールド', 'floral', false),
  ('honey-pomelo', 'honey pomelo', '文旦', 'gourmand', false),
  ('cotton-candy', 'cotton candy', '綿菓子', 'gourmand', false),
  ('sweet-pea', 'sweet pea', 'スイートピー', 'other', false),
  ('leaves', 'leaves', '葉', 'green', false),
  ('sea-breeze', 'sea breeze', '潮風', 'aquatic', false),
  ('linden-blossom', 'linden blossom', 'リンデンブロッサム', 'white_floral', false),
  ('gasoline', 'gasoline', 'ガソリン', 'other', true),
  ('dust', 'dust', '埃', 'other', true),
  ('charcoal', 'charcoal', '炭', 'other', true),
  ('passion-flower', 'passion flower', 'パッションフラワー', 'floral', false),
  ('brown-sugar', 'brown sugar', '黒糖', 'gourmand', false),
  ('date', 'date', 'デーツ', 'fruity', false),
  ('akigalawood', 'akigalawood', 'アキガラウッド', 'woody', false),
  ('tomato-leaf', 'tomato leaf', 'トマトリーフ', 'green', false),
  ('cognac', 'cognac', 'コニャック', 'boozy', false),
  ('birch-leaf', 'birch leaf', 'バーチリーフ', 'woody', false),
  ('lemon-blossom', 'lemon blossom', 'レモンの花', 'white_floral', false),
  ('marjoram', 'marjoram', 'マジョラム', 'herbal', false),
  ('tar', 'tar', 'タール', 'tobacco', true),
  ('rubber', 'rubber', 'ゴム', 'other', true),
  ('tobacco-flower', 'tobacco flower', 'タバコの花', 'tobacco', false),
  ('fermented-almond', 'fermented almond', '発酵アーモンド', 'gourmand', false),
  ('champagne', 'champagne', 'シャンパン', 'boozy', false),
  ('toffee', 'toffee', 'トフィー', 'gourmand', false),
  ('iso-e-super', 'iso e super', 'イソイースーパー', 'synthetic', false),
  ('brine', 'brine', '潮', 'other', true),
  ('asphalt', 'asphalt', 'アスファルト', 'other', true),
  ('litsea-cubeba', 'litsea cubeba', 'リッツェアクベバ', 'aquatic', false),
  ('mace', 'mace', 'メース', 'spicy', false),
  ('starfruit', 'starfruit', 'スターフルーツ', 'fruity', false),
  ('fennel', 'fennel', 'フェンネル', 'spicy', false),
  ('oregano', 'oregano', 'オレガノ', 'herbal', false),
  ('stone-pine', 'stone pine', 'イタリアカサマツ', 'woody', false),
  ('whisky', 'whisky', 'ウイスキー', 'boozy', false),
  ('mandarin-orange-leaf', 'mandarin orange leaf', null, 'citrus', false),
  ('vermouth', 'vermouth', 'ベルモット', 'other', false),
  ('clover', 'clover', 'クローバー', 'floral', false),
  ('black-leather', 'black leather', 'ブラックレザー', 'leather', false),
  ('carrot', 'carrot', '人参', 'other', false),
  ('cannabis', 'cannabis', 'カンナビス', 'other', false),
  ('deer-musk', 'deer musk', '麝香', 'animalic', false),
  ('copaiba', 'copaiba', 'コパイバ', 'balsamic', false),
  ('camellia', 'camellia', '椿', 'floral', false),
  ('pear-blossom', 'pear blossom', '洋梨の花', 'white_floral', false),
  ('grape', 'grape', '葡萄', 'fruity', false),
  ('lemon-leaf', 'lemon leaf', 'レモンリーフ', 'citrus', false),
  ('jasmine-tea', 'jasmine tea', 'ジャスミンティー', 'tea', false),
  ('algae', 'algae', '藻', 'aquatic', false),
  ('blue-lotus', 'blue lotus', '青蓮', 'other', false),
  ('ash', 'ash', '灰', 'other', true),
  ('pistachio', 'pistachio', 'ピスタチオ', 'gourmand', false),
  ('sand', 'sand', '砂', 'other', false),
  ('green-pepper', 'green pepper', 'グリーンペッパー', 'spicy', false),
  ('palo-santo', 'palo santo', 'パロサント', 'other', false),
  ('orcanox', 'orcanox', 'オルカノックス', 'other', false),
  ('white-chocolate', 'white chocolate', 'ホワイトチョコレート', 'gourmand', false),
  ('white-freesia', 'white freesia', '白フリージア', 'white_floral', false),
  ('kelp', 'kelp', '昆布', 'other', false),
  ('geranium-leaf', 'geranium leaf', 'ゼラニウムリーフ', 'floral', false),
  ('black-orchid', 'black orchid', 'ブラックオーキッド', 'white_floral', false),
  ('almond-milk', 'almond milk', null, 'gourmand', false),
  ('birch-tar', 'birch tar', 'バーチタール', 'leather', false),
  ('candied-apple', 'candied apple', null, 'fruity', false),
  ('earthy', 'earthy', null, 'earthy', false),
  ('new-caledonian-sandalwood', 'new caledonian sandalwood', null, 'woody', false),
  ('exotic-woods', 'exotic woods', null, 'woody', false),
  ('hinoki-cypress', 'hinoki cypress', null, 'woody', false),
  ('black-cherry', 'black cherry', null, 'fruity', false),
  ('mineral', 'mineral', null, 'mineral', false),
  ('cotton-flower', 'cotton flower', null, 'floral', false),
  ('tea-rose', 'tea rose', null, 'tea', false),
  ('green-pear', 'green pear', null, 'fruity', false),
  ('white-ambergris', 'white ambergris', null, 'balsamic', false),
  ('red-thyme', 'red thyme', null, 'herbal', false),
  ('comorian-ylang-ylang', 'comorian ylang-ylang', null, 'other', false),
  ('white-oud', 'white oud', null, 'woody', false),
  ('palmarosa', 'palmarosa', null, 'other', false),
  ('dew-drop', 'dew drop', null, 'other', false),
  ('crystal-musk', 'crystal musk', null, 'musk', false),
  ('banana', 'banana', 'バナナ', 'fruity', false),
  ('bell-pepper', 'bell pepper', null, 'spicy', false),
  ('hinoki-wood', 'hinoki wood', null, 'woody', false),
  ('pink-freesia', 'pink freesia', null, 'white_floral', false),
  ('peach-nectar', 'peach nectar', null, 'fruity', false),
  ('white-iris', 'white iris', null, 'floral', false),
  ('reseda', 'reseda', null, 'other', false),
  ('white-moss', 'white moss', null, 'earthy', false),
  ('black-musk', 'black musk', null, 'musk', false),
  ('sensual-skin', 'sensual skin', null, 'animalic', false),
  ('mock-orange', 'mock-orange', null, 'citrus', false),
  ('rose-leaf', 'rose leaf', null, 'floral', false),
  ('bamboo-leaf', 'bamboo leaf', null, 'green', false),
  ('turmeric', 'turmeric', 'ターメリック', 'herbal', false),
  ('acacia', 'acacia', 'アカシア', 'white_floral', false),
  ('hyraceum', 'hyraceum', 'ハイラシウム', 'animalic', false),
  ('fir-resin', 'fir resin', null, 'balsamic', false),
  ('black-rose', 'black rose', null, 'floral', false),
  ('water-hyacinth', 'water hyacinth', null, 'green', false),
  ('clearwood', 'clearwood', null, 'woody', false),
  ('white-thyme', 'white thyme', null, 'herbal', false),
  ('rice', 'rice', '米', 'gourmand', false),
  ('watery-fruits', 'watery fruits', null, 'fruity', false),
  ('bitter-orange-blossom', 'bitter orange blossom', null, 'white_floral', false),
  ('white-orchid', 'white orchid', 'ホワイトオーキッド', 'white_floral', false),
  ('soil', 'soil', '土', 'earthy', false),
  ('star-jasmine', 'star jasmine', 'テイカカズラ', 'white_floral', false),
  ('vodka', 'vodka', 'ウォッカ', 'boozy', false),
  ('lemon-petitgrain', 'lemon petitgrain', null, 'citrus', false),
  ('metallic-notes', 'metallic notes', 'メタリックノート', 'mineral', false),
  ('tropical-fruits', 'tropical fruits', 'トロピカルフルーツ', 'fruity', false),
  ('spikenard', 'spikenard', null, 'herbal', false),
  ('honeydew-melon', 'honeydew melon', null, 'fruity', false),
  ('tulip', 'tulip', 'チューリップ', 'floral', false),
  ('datura', 'datura', 'ダチュラ', 'floral', false),
  ('olive-wood', 'olive wood', null, 'woody', false),
  ('key-lime', 'key lime', 'キーライム', 'citrus', false),
  ('cotton', 'cotton', 'コットン', 'green', false),
  ('angelica-seed', 'angelica seed', null, 'herbal', false),
  ('ginger-flower', 'ginger flower', 'ジンジャーフラワー', 'white_floral', false),
  ('spindrift', 'spindrift', null, 'aquatic', false),
  ('paradisone', 'paradisone', null, 'synthetic', false),
  ('chestnut', 'chestnut', '栗', 'woody', false),
  ('costus', 'costus', 'コスタス', 'animalic', false),
  ('raspberry-leaf', 'raspberry leaf', null, 'green', false),
  ('salted-caramel', 'salted caramel', '塩キャラメル', 'gourmand', false),
  ('sugar-cane', 'sugar cane', null, 'gourmand', false),
  ('plum-blossom', 'plum blossom', '梅の花', 'floral', false),
  ('spruce', 'spruce', 'スプルース', 'woody', false),
  ('pelargonium', 'pelargonium', null, 'other', false),
  ('cane-sugar', 'cane sugar', 'サトウキビ', 'gourmand', false),
  ('amaretto', 'amaretto', 'アマレット', 'boozy', false),
  ('grapefruit-blossom', 'grapefruit blossom', null, 'white_floral', false),
  ('dragon-fruit', 'dragon fruit', null, 'fruity', false),
  ('pineapple-leaf', 'pineapple leaf', null, 'green', false),
  ('fougere', 'fougère', null, 'other', false),
  ('poppy', 'poppy', 'ポピー', 'floral', false),
  ('aquatic-flowers', 'aquatic flowers', null, 'white_floral', false),
  ('sunflower', 'sunflower', 'ひまわり', 'floral', false),
  ('bergamot-zest', 'bergamot zest', 'ベルガモットの皮', 'citrus', false),
  ('water-mint', 'water mint', null, 'herbal', false),
  ('ice', 'ice', null, 'other', false),
  ('calamus', 'calamus', '菖蒲', 'herbal', false),
  ('blond-tobacco', 'blond tobacco', 'ブロンドタバコ', 'tobacco', false),
  ('linden-tree', 'linden tree', null, 'white_floral', false),
  ('white-honey', 'white honey', null, 'gourmand', false),
  ('cascalone', 'cascalone', null, 'synthetic', false),
  ('orange-blossom-water', 'orange blossom water', null, 'white_floral', false),
  ('boronia', 'boronia', null, 'floral', false),
  ('apricot-blossom', 'apricot blossom', null, 'floral', false),
  ('red-ginger', 'red ginger', null, 'spicy', false),
  ('exotic-blossoms', 'exotic blossoms', null, 'floral', false),
  ('white-leather', 'white leather', null, 'leather', false),
  ('olive-blossom', 'olive blossom', null, 'white_floral', false),
  ('pear-sorbet', 'pear sorbet', null, 'fruity', false),
  ('green-cardamom', 'green cardamom', 'グリーンカルダモン', 'spicy', false),
  ('frankincense-resin', 'frankincense resin', null, 'balsamic', false),
  ('seagrass', 'seagrass', '海藻', 'green', false),
  ('crystallised-moss', 'crystallised moss', null, 'earthy', false),
  ('buchu', 'buchu', null, 'green', false),
  ('vanilla-cream', 'vanilla cream', 'バニラクリーム', 'gourmand', false),
  ('dewberry', 'dewberry', null, 'fruity', false),
  ('gin', 'gin', 'ジン', 'boozy', false),
  ('kaffir-lime', 'kaffir lime', 'カフィアライム', 'citrus', false),
  ('canary-islands-juniper', 'canary islands juniper', null, 'other', false),
  ('mandarin-orange-blossom', 'mandarin orange blossom', null, 'white_floral', false),
  ('fenugreek', 'fenugreek', null, 'herbal', false),
  ('candied-fruits', 'candied fruits', '砂糖漬けの果実', 'fruity', false),
  ('sweet-acacia', 'sweet acacia', null, 'white_floral', false),
  ('sour-cherry', 'sour cherry', 'サワーチェリー', 'fruity', false),
  ('tamarind', 'tamarind', 'タマリンド', 'fruity', false),
  ('prune', 'prune', 'プルーン', 'fruity', false),
  ('queen-of-the-night', 'queen-of-the-night', null, 'white_floral', false),
  ('cactus-blossom', 'cactus blossom', null, 'white_floral', false),
  ('flowers', 'flowers', '花', 'floral', false),
  ('peach-skin', 'peach skin', '桃の産毛', 'fruity', false),
  ('petalia', 'petalia', null, 'synthetic', false),
  ('green-lemon', 'green lemon', null, 'citrus', false),
  ('amaryllis', 'amaryllis', null, 'floral', false),
  ('white-lotus', 'white lotus', '白蓮', 'white_floral', false),
  ('shiso', 'shiso', '紫蘇', 'green', false),
  ('creamy-notes', 'creamy notes', 'クリーミーノート', 'gourmand', false),
  ('rain', 'rain', null, 'aquatic', false),
  ('black-locust', 'black locust', null, 'woody', false),
  ('talcum', 'talcum', 'タルカムパウダー', 'powdery', false),
  ('sugar-powder', 'sugar powder', null, 'gourmand', false),
  ('roasted-almond', 'roasted almond', null, 'gourmand', false),
  ('parma-violet', 'parma violet', 'パルマスミレ', 'floral', false),
  ('sesame', 'sesame', null, 'other', false),
  ('finger-lime', 'finger lime', null, 'citrus', false),
  ('blue-atlas-cedar', 'blue atlas cedar', null, 'woody', false),
  ('butter', 'butter', 'バター', 'gourmand', false),
  ('truffle', 'truffle', 'トリュフ', 'gourmand', false),
  ('red-peony', 'red peony', null, 'floral', false),
  ('roasted-tonka-bean', 'roasted tonka bean', null, 'gourmand', false),
  ('pittosporum', 'pittosporum', null, 'woody', false),
  ('yellow-freesia', 'yellow freesia', null, 'white_floral', false),
  ('pink-rose', 'pink rose', null, 'floral', false),
  ('ambrettolide', 'ambrettolide', null, 'musk', false),
  ('blackcurrant-liqueur', 'blackcurrant liqueur', null, 'boozy', false),
  ('celery', 'celery', 'セロリ', 'herbal', false),
  ('pink-lotus', 'pink lotus', null, 'other', false),
  ('white-gingerlily', 'white gingerlily', null, 'white_floral', false),
  ('apricot-nectar', 'apricot nectar', null, 'fruity', false),
  ('salicylate', 'salicylate', null, 'synthetic', false),
  ('liatris-spicata', 'liatris spicata', null, 'other', false),
  ('williams-pear', 'williams pear', null, 'fruity', false),
  ('kahili-ginger', 'kahili ginger', null, 'white_floral', false),
  ('fig-milk', 'fig milk', null, 'fruity', false),
  ('minneola-tangelo', 'minneola tangelo', null, 'fruity', false),
  ('shiso-leaf', 'shiso leaf', '紫蘇の葉', 'green', false),
  ('saffron-blossom', 'saffron blossom', null, 'floral', false),
  ('grapefruit-zest', 'grapefruit zest', 'グレープフルーツの皮', 'citrus', false),
  ('stephanotis', 'stephanotis', 'ステファノティス', 'white_floral', false),
  ('blue-iris', 'blue iris', null, 'floral', false),
  ('green-almond', 'green almond', null, 'gourmand', false),
  ('dragee', 'dragée', null, 'gourmand', false),
  ('earl-grey-tea', 'earl grey tea', null, 'tea', false),
  ('fig-wood', 'fig wood', null, 'woody', false),
  ('orange-leaf', 'orange leaf', 'オレンジリーフ', 'citrus', false),
  ('rice-powder', 'rice powder', '米粉', 'powdery', false),
  ('dulce-de-leche', 'dulce de leche', 'ドゥルセ・デ・レチェ', 'gourmand', false),
  ('mate-tea', 'maté tea', null, 'tea', false),
  ('lichen', 'lichen', '地衣類', 'earthy', false),
  ('bitter-orange-leaf', 'bitter orange leaf', null, 'citrus', false),
  ('jonquil', 'jonquil', null, 'other', false),
  ('bay-rum', 'bay rum', null, 'boozy', false),
  ('rose-hip', 'rose hip', 'ローズヒップ', 'floral', false),
  ('rhubarb-leaf', 'rhubarb leaf', null, 'green', false),
  ('hemp', 'hemp', null, 'other', false),
  ('sequoia', 'sequoia', 'セコイア', 'woody', false),
  ('hyssop', 'hyssop', 'ヒソップ', 'herbal', false),
  ('black-cardamom', 'black cardamom', null, 'spicy', false),
  ('dark-woods', 'dark woods', 'ダークウッド', 'woody', false),
  ('nuts', 'nuts', 'ナッツ', 'gourmand', false),
  ('currant-leaf', 'currant leaf', null, 'green', false),
  ('acai', 'açaí', null, 'fruity', false),
  ('matcha', 'matcha', '抹茶', 'tea', false),
  ('fir-needle', 'fir needle', null, 'other', false),
  ('mineral-amber', 'mineral amber', null, 'balsamic', false),
  ('cabreuva', 'cabreuva', null, 'other', false),
  ('muscenone', 'muscenone', null, 'musk', false),
  ('cade-juniper', 'cade juniper', null, 'woody', false),
  ('basmati-rice', 'basmati rice', null, 'gourmand', false),
  ('camphor', 'camphor', 'カンファー', 'herbal', false),
  ('georgywood', 'georgywood', null, 'woody', false),
  ('casablanca-lily', 'casablanca lily', null, 'white_floral', false),
  ('black-violet', 'black violet', null, 'floral', false)
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_ja = excluded.name_ja,
  family = excluded.family,
  needs_review = excluded.needs_review;

insert into note_aliases (alias, note_id)
select v.alias, n.id from (values
  ('egyptian acacia', 'acacia'),
  ('algae absolute', 'algae'),
  ('sicilian almond', 'almond'),
  ('italian almond', 'almond'),
  ('persian almond', 'almond'),
  ('sicilian almond blossom', 'almond-blossom'),
  ('amberwood', 'amber'),
  ('white amber', 'amber'),
  ('black amber', 'amber'),
  ('crystal amber', 'amber'),
  ('amber xtreme', 'amber'),
  ('ambreine', 'amber'),
  ('amber notes', 'amber'),
  ('indian amber', 'amber'),
  ('tunisian amber', 'amber'),
  ('persian amber', 'amber'),
  ('oriental amber', 'amber'),
  ('greek amber', 'amber'),
  ('amber absolute', 'amber'),
  ('indian ambergris', 'ambergris'),
  ('ambergris absolute', 'ambergris'),
  ('irish ambergris', 'ambergris'),
  ('russian ambergris', 'ambergris'),
  ('ambrette seed absolute', 'ambrette-seed'),
  ('indian ambrette seed', 'ambrette-seed'),
  ('peruvian ambrette seed', 'ambrette-seed'),
  ('peruvian ambrette seed absolute', 'ambrette-seed'),
  ('australian ambrette seed', 'ambrette-seed'),
  ('ambrox', 'ambroxan'),
  ('ambrofix', 'ambroxan'),
  ('haitian amyris', 'amyris'),
  ('caribbean amyris', 'amyris'),
  ('angelica root', 'angelica'),
  ('french angelica root', 'angelica'),
  ('angelica root co2', 'angelica'),
  ('french angelica', 'angelica'),
  ('aniseed', 'anise'),
  ('granny smith apple', 'apple'),
  ('italian apple', 'apple'),
  ('canadian apple', 'apple'),
  ('dried apricot', 'apricot'),
  ('marine notes', 'aquatic'),
  ('aquatic notes', 'aquatic'),
  ('calone', 'aquatic'),
  ('egyptian balsam', 'balsam'),
  ('bamboo absolute', 'bamboo'),
  ('tibetan bamboo', 'bamboo'),
  ('egyptian basil', 'basil'),
  ('thai basil', 'basil'),
  ('basil absolute', 'basil'),
  ('indian bay leaf', 'bay-leaf'),
  ('beeswax absolute', 'beeswax'),
  ('french beeswax', 'beeswax'),
  ('laotian beeswax', 'beeswax'),
  ('french beeswax absolute', 'beeswax'),
  ('styrax', 'benzoin'),
  ('benzoin siam', 'benzoin'),
  ('sumatra benzoin', 'benzoin'),
  ('benzoin absolute', 'benzoin'),
  ('benzoin siam absolute', 'benzoin'),
  ('thai benzoin', 'benzoin'),
  ('styrax absolute', 'benzoin'),
  ('indonesian styrax', 'benzoin'),
  ('japanese styrax', 'benzoin'),
  ('italian bergamot', 'bergamot'),
  ('calabrian bergamot', 'bergamot'),
  ('sicilian bergamot', 'bergamot'),
  ('french bergamot', 'bergamot'),
  ('bergamot absolute', 'bergamot'),
  ('bergamot co2', 'bergamot'),
  ('italian bergamot zest', 'bergamot-zest'),
  ('wild berries', 'berries'),
  ('dried berries', 'berries'),
  ('birch wood', 'birch'),
  ('silver birch', 'birch'),
  ('tuscan birch', 'birch'),
  ('italian birch', 'birch'),
  ('siberian birch', 'birch'),
  ('russian birch', 'birch'),
  ('italian birch wood', 'birch'),
  ('russian birch tar', 'birch-tar'),
  ('moroccan bitter almond', 'bitter-almond'),
  ('sicilian bitter orange', 'bitter-orange'),
  ('italian bitter orange', 'bitter-orange'),
  ('spanish bitter orange', 'bitter-orange'),
  ('brazilian bitter orange', 'bitter-orange'),
  ('egyptian bitter orange', 'bitter-orange'),
  ('paraguayan bitter orange', 'bitter-orange'),
  ('bitter orange absolute', 'bitter-orange'),
  ('calabrian bitter orange', 'bitter-orange'),
  ('african bitter orange', 'bitter-orange'),
  ('moroccan bitter orange blossom', 'bitter-orange-blossom'),
  ('italian bitter orange blossom', 'bitter-orange-blossom'),
  ('bitter orange blossom absolute', 'bitter-orange-blossom'),
  ('indian black pepper', 'black-pepper'),
  ('zanzibar black pepper', 'black-pepper'),
  ('indonesian black pepper', 'black-pepper'),
  ('black pepper absolute', 'black-pepper'),
  ('black tea absolute', 'black-tea'),
  ('chinese black tea', 'black-tea'),
  ('indian black tea', 'black-tea'),
  ('blackcurrant absolute', 'blackcurrant'),
  ('french blackcurrant', 'blackcurrant'),
  ('italian blackcurrant', 'blackcurrant'),
  ('egyptian blackcurrant', 'blackcurrant'),
  ('english blackcurrant', 'blackcurrant'),
  ('polish blackcurrant', 'blackcurrant'),
  ('blackcurrant co2', 'blackcurrant'),
  ('french blackcurrant absolute', 'blackcurrant'),
  ('blackcurrant leaf', 'blackcurrant-bud'),
  ('blackcurrant bud absolute', 'blackcurrant-bud'),
  ('french blackcurrant bud absolute', 'blackcurrant-bud'),
  ('french blackcurrant bud', 'blackcurrant-bud'),
  ('blackcurrant bud co2', 'blackcurrant-bud'),
  ('blond tobacco absolute', 'blond-tobacco'),
  ('sicilian blood orange', 'blood-orange'),
  ('italian blood orange', 'blood-orange'),
  ('calabrian blood orange', 'blood-orange'),
  ('oriental blossoms', 'blossoms'),
  ('french blossoms', 'blossoms'),
  ('blue lotus absolute', 'blue-lotus'),
  ('boronia absolute', 'boronia'),
  ('broom absolute', 'broom'),
  ('spanish broom', 'broom'),
  ('italian broom absolute', 'broom'),
  ('italian broom', 'broom'),
  ('french broom', 'broom'),
  ('butter co2', 'butter'),
  ('butter absolute', 'butter'),
  ('brazilian cabreuva', 'cabreuva'),
  ('indian calamus', 'calamus'),
  ('egyptian calamus', 'calamus'),
  ('japanese camellia', 'camellia'),
  ('moroccan cannabis', 'cannabis'),
  ('turkish caramel', 'caramel'),
  ('guatemala cardamom', 'cardamom'),
  ('indian cardamom', 'cardamom'),
  ('cardamom absolute', 'cardamom'),
  ('cardamom co2', 'cardamom'),
  ('egyptian cardamom', 'cardamom'),
  ('zanzibar cardamom', 'cardamom'),
  ('african cardamom', 'cardamom'),
  ('nepalese cardamom', 'cardamom'),
  ('french carnation', 'carnation'),
  ('carnation absolute', 'carnation'),
  ('egyptian carnation', 'carnation'),
  ('carrot absolute', 'carrot'),
  ('french carrot', 'carrot'),
  ('french carrot seed', 'carrot-seed'),
  ('cashmere wood', 'cashmeran'),
  ('cashmere', 'cashmeran'),
  ('chinese cassia', 'cassia'),
  ('cassia absolute', 'cassia'),
  ('castoreum absolute', 'castoreum'),
  ('russian castoreum', 'castoreum'),
  ('canadian castoreum', 'castoreum'),
  ('himalaya cedar leaf', 'cedar-leaf'),
  ('canadian cedar leaf', 'cedar-leaf'),
  ('cedar', 'cedarwood'),
  ('virginia cedar', 'cedarwood'),
  ('atlas cedar', 'cedarwood'),
  ('texas cedar', 'cedarwood'),
  ('lebanon cedar', 'cedarwood'),
  ('himalaya cedar', 'cedarwood'),
  ('french cedar', 'cedarwood'),
  ('chinese cedar', 'cedarwood'),
  ('cuban cedar', 'cedarwood'),
  ('canadian cedar', 'cedarwood'),
  ('australian cedar wood', 'cedarwood'),
  ('cedarwood absolute', 'cedarwood'),
  ('atlas cedar absolute', 'cedarwood'),
  ('italian cedar', 'cedarwood'),
  ('cuban cedar wood', 'cedarwood'),
  ('roman chamomile', 'chamomile'),
  ('moroccan chamomile', 'chamomile'),
  ('champaca flower', 'champaca'),
  ('champaca absolute', 'champaca'),
  ('wild cherry', 'cherry'),
  ('turkish cherry', 'cherry'),
  ('japanese cherry blossom', 'cherry-blossom'),
  ('portuguese chestnut', 'chestnut'),
  ('red pepper', 'chili'),
  ('peruvian red pepper', 'chili'),
  ('mexican chocolate', 'chocolate'),
  ('french chocolate', 'chocolate'),
  ('italian chocolate', 'chocolate'),
  ('ceylon cinnamon', 'cinnamon'),
  ('cinnamon leaf', 'cinnamon'),
  ('madagascan cinnamon', 'cinnamon'),
  ('laotian cinnamon', 'cinnamon'),
  ('cinnamon absolute', 'cinnamon'),
  ('ceylon cinnamon leaf', 'cinnamon'),
  ('indonesian cinnamon', 'cinnamon'),
  ('cistus absolute', 'cistus'),
  ('spanish cistus', 'cistus'),
  ('spanish cistus absolute', 'cistus'),
  ('omani cistus', 'cistus'),
  ('corsican cistus', 'cistus'),
  ('french cistus', 'cistus'),
  ('portuguese cistus', 'cistus'),
  ('moroccan cistus absolute', 'cistus'),
  ('spanish cistus concrete', 'cistus'),
  ('italian citron', 'citron'),
  ('sicilian citron', 'citron'),
  ('calabrian citron', 'citron'),
  ('corsican citron', 'citron'),
  ('civet absolute', 'civet'),
  ('indian civet', 'civet'),
  ('indian civet absolute', 'civet'),
  ('ethiopian civet', 'civet'),
  ('french clary sage', 'clary-sage'),
  ('clary sage absolute', 'clary-sage'),
  ('french clary sage absolute', 'clary-sage'),
  ('russian clary sage', 'clary-sage'),
  ('madagascan clove', 'clove'),
  ('indonesian clove', 'clove'),
  ('zanzibar clove', 'clove'),
  ('ceylonese clove', 'clove'),
  ('clove absolute', 'clove'),
  ('cocoa absolute', 'cocoa'),
  ('cocoa bean', 'cocoa'),
  ('cocoa bean absolute', 'cocoa'),
  ('french cocoa', 'cocoa'),
  ('coconut co2', 'coconut'),
  ('thai coconut', 'coconut'),
  ('coconut absolute', 'coconut'),
  ('caribbean coconut', 'coconut'),
  ('coffee bean', 'coffee'),
  ('coffee absolute', 'coffee'),
  ('coffee co2', 'coffee'),
  ('turkish coffee', 'coffee'),
  ('brazilian coffee', 'coffee'),
  ('colombian coffee', 'coffee'),
  ('arabian coffee', 'coffee'),
  ('peruvian coffee bean', 'coffee'),
  ('kenyan coffee', 'coffee'),
  ('brazilian coffee absolute', 'coffee'),
  ('ethiopian coffee absolute', 'coffee'),
  ('ethiopian coffee', 'coffee'),
  ('copaiba balsam', 'copaiba'),
  ('brazilian copaiba balsam', 'copaiba'),
  ('russian coriander', 'coriander'),
  ('french coriander', 'coriander'),
  ('coriander co2', 'coriander'),
  ('mexican coriander', 'coriander'),
  ('indian coriander', 'coriander'),
  ('russian coriander seed', 'coriander-seed'),
  ('moroccan coriander seed', 'coriander-seed'),
  ('costus absolute', 'costus'),
  ('irish cream', 'cream'),
  ('egyptian cumin', 'cumin'),
  ('cumin absolute', 'cumin'),
  ('iranian cumin', 'cumin'),
  ('nootka cypress', 'cypress'),
  ('italian cypress', 'cypress'),
  ('french cypress', 'cypress'),
  ('cypress absolute', 'cypress'),
  ('tuscan cypress', 'cypress'),
  ('spanish cypress', 'cypress'),
  ('indian cypriol', 'cypriol'),
  ('greek cypriol', 'cypriol'),
  ('ceylonese cypriol', 'cypriol'),
  ('italian dark chocolate', 'dark-chocolate'),
  ('turkish date', 'date'),
  ('davana absolute', 'davana'),
  ('siberian deer musk', 'deer-musk'),
  ('himalayan deer musk', 'deer-musk'),
  ('kashmiri deer musk', 'deer-musk'),
  ('tibetan deer musk', 'deer-musk'),
  ('nepalese deer musk', 'deer-musk'),
  ('earthy notes', 'earthy'),
  ('african ebony', 'ebony'),
  ('elemi resin', 'elemi'),
  ('persian elemi', 'elemi'),
  ('malayan elemi', 'elemi'),
  ('french elemi', 'elemi'),
  ('chinese eucalyptus', 'eucalyptus'),
  ('greek eucalyptus', 'eucalyptus'),
  ('brazilian eucalyptus', 'eucalyptus'),
  ('wild fennel', 'fennel'),
  ('italian fennel', 'fennel'),
  ('greek fennel', 'fennel'),
  ('fenugreek absolute', 'fenugreek'),
  ('moroccan fenugreek', 'fenugreek'),
  ('wild fig', 'fig'),
  ('italian fig', 'fig'),
  ('fir absolute', 'fir'),
  ('siberian fir absolute', 'fir'),
  ('siberian fir', 'fir'),
  ('balsam fir', 'fir-balsam'),
  ('fir balsam absolute', 'fir-balsam'),
  ('canadian fir balsam', 'fir-balsam'),
  ('balsam fir absolute', 'fir-balsam'),
  ('canadian fir balsam absolute', 'fir-balsam'),
  ('siberian fir needle', 'fir-needle'),
  ('canadian fir resin', 'fir-resin'),
  ('wild flowers', 'flowers'),
  ('fougère notes', 'fougere'),
  ('frangipani absolute', 'frangipani'),
  ('thai frangipani', 'frangipani'),
  ('indian frangipani', 'frangipani'),
  ('mexican frangipani', 'frangipani'),
  ('venezuelan frangipani', 'frangipani'),
  ('somalian frankincense', 'frankincense'),
  ('omani frankincense', 'frankincense'),
  ('ethiopian frankincense', 'frankincense'),
  ('incense material', 'frankincense'),
  ('frankincense absolute', 'frankincense'),
  ('incense', 'frankincense'),
  ('frankincense co2 absolute', 'frankincense'),
  ('african frankincense', 'frankincense'),
  ('indian frankincense', 'frankincense'),
  ('frankincense co2', 'frankincense'),
  ('chinese incense', 'frankincense'),
  ('somalian frankincense absolute', 'frankincense'),
  ('frankincense oil', 'frankincense'),
  ('incense absolute', 'frankincense'),
  ('persian frankincense', 'frankincense'),
  ('japanese incense', 'frankincense'),
  ('freesia absolute', 'freesia'),
  ('italian freesia', 'freesia'),
  ('wild freesia', 'freesia'),
  ('paraguayan gaiac wood', 'gaiac-wood'),
  ('argentinian gaiac wood', 'gaiac-wood'),
  ('caribbean gaiac wood', 'gaiac-wood'),
  ('brazilian gaiac wood', 'gaiac-wood'),
  ('peruvian gaiac wood', 'gaiac-wood'),
  ('colombian gaiac wood', 'gaiac-wood'),
  ('indonesian gaiac wood', 'gaiac-wood'),
  ('gaiac wood absolute', 'gaiac-wood'),
  ('persian galbanum', 'galbanum'),
  ('spanish galbanum', 'galbanum'),
  ('turkish galbanum', 'galbanum'),
  ('indian galbanum', 'galbanum'),
  ('brazilian gardenia', 'gardenia'),
  ('gardenia absolute', 'gardenia'),
  ('french gardenia', 'gardenia'),
  ('chinese gardenia co2', 'gardenia'),
  ('chinese gardenia', 'gardenia'),
  ('italian gardenia', 'gardenia'),
  ('egyptian geranium', 'geranium'),
  ('bourbon geranium', 'geranium'),
  ('madagascan geranium', 'geranium'),
  ('geranium absolute', 'geranium'),
  ('african geranium', 'geranium'),
  ('chinese geranium', 'geranium'),
  ('bulgarian geranium', 'geranium'),
  ('moroccan geranium', 'geranium'),
  ('egyptian bourbon geranium', 'geranium'),
  ('french bourbon geranium', 'geranium'),
  ('egyptian geranium leaf', 'geranium-leaf'),
  ('madagascan ginger', 'ginger'),
  ('chinese ginger', 'ginger'),
  ('ginger co2', 'ginger'),
  ('thai ginger', 'ginger'),
  ('indian ginger', 'ginger'),
  ('ginger absolute', 'ginger'),
  ('laotian ginger', 'ginger'),
  ('indonesian ginger', 'ginger'),
  ('pink grapefruit', 'grapefruit'),
  ('red grapefruit', 'grapefruit'),
  ('sicilian grapefruit', 'grapefruit'),
  ('italian grapefruit', 'grapefruit'),
  ('moroccan grapefruit', 'grapefruit'),
  ('calabrian grapefruit', 'grapefruit'),
  ('grapefruit absolute', 'grapefruit'),
  ('chinese grapefruit', 'grapefruit'),
  ('mexican pink grapefruit', 'grapefruit'),
  ('sicilian pink grapefruit', 'grapefruit'),
  ('moroccan grapefruit blossom', 'grapefruit-blossom'),
  ('wild grass', 'grass'),
  ('italian green apple', 'green-apple'),
  ('madagascan green cardamom', 'green-cardamom'),
  ('japanese green tea', 'green-tea'),
  ('green tea absolute', 'green-tea'),
  ('chinese green tea', 'green-tea'),
  ('gurjum balsam', 'gurjun-balsam'),
  ('malaysian gurjum balsam', 'gurjun-balsam'),
  ('thai gurjun balsam', 'gurjun-balsam'),
  ('hay absolute', 'hay'),
  ('french hay', 'hay'),
  ('italian heliotrope', 'heliotrope'),
  ('heliotrope absolute', 'heliotrope'),
  ('indian hemp', 'hemp'),
  ('french hemp', 'hemp'),
  ('wild herbs', 'herbs'),
  ('african herbs', 'herbs'),
  ('hibiscus absolute', 'hibiscus'),
  ('wild honey', 'honey'),
  ('honey absolute', 'honey'),
  ('laotian honey', 'honey'),
  ('english honey', 'honey'),
  ('italian honey', 'honey'),
  ('french honey', 'honey'),
  ('japanese honeysuckle', 'honeysuckle'),
  ('italian honeysuckle', 'honeysuckle'),
  ('tuscan hyacinth', 'hyacinth'),
  ('wild hyacinth', 'hyacinth'),
  ('hyraceum absolute', 'hyraceum'),
  ('ice accord', 'ice'),
  ('everlasting flower', 'immortelle'),
  ('immortelle absolute', 'immortelle'),
  ('corsican immortelle', 'immortelle'),
  ('everlasting flower absolute', 'immortelle'),
  ('spanish immortelle', 'immortelle'),
  ('orris root', 'iris'),
  ('florentine iris', 'iris'),
  ('orris butter', 'iris'),
  ('orris concrete', 'iris'),
  ('orris absolute', 'iris'),
  ('iris pallida', 'iris'),
  ('violet root', 'iris'),
  ('florentine iris absolute', 'iris'),
  ('italian iris', 'iris'),
  ('moroccan orris butter', 'iris'),
  ('french iris', 'iris'),
  ('iris pallida concrete', 'iris'),
  ('chinese orris butter', 'iris'),
  ('wild iris', 'iris'),
  ('italian iris pallida', 'iris'),
  ('italian iris concrete', 'iris'),
  ('french iris absolute', 'iris'),
  ('italian orris root', 'iris'),
  ('italian iris absolute', 'iris'),
  ('french orris butter', 'iris'),
  ('orris root co2', 'iris'),
  ('french iris concrete', 'iris'),
  ('iris co2', 'iris'),
  ('french orris root', 'iris'),
  ('chinese iris absolute', 'iris'),
  ('orris butter absolute', 'iris'),
  ('chinese iris concrete', 'iris'),
  ('siberian iris', 'iris'),
  ('italian orris butter', 'iris'),
  ('florentine orris butter', 'iris'),
  ('moroccan iris concrete', 'iris'),
  ('iso-e-super', 'iso-e-super'),
  ('jasmine absolute', 'jasmine'),
  ('egyptian jasmine', 'jasmine'),
  ('grasse jasmine', 'jasmine'),
  ('jasminum auriculatum', 'jasmine'),
  ('jasminum grandiflorum', 'jasmine'),
  ('night-blooming jasmine', 'jasmine'),
  ('water jasmine', 'jasmine'),
  ('egyptian jasmine absolute', 'jasmine'),
  ('moroccan jasmine', 'jasmine'),
  ('jasminum grandiflorum absolute', 'jasmine'),
  ('jasminum auriculatum absolute', 'jasmine'),
  ('italian jasmine', 'jasmine'),
  ('wild jasmine', 'jasmine'),
  ('egyptian jasminum grandiflorum', 'jasmine'),
  ('chinese jasmine', 'jasmine'),
  ('french jasmine', 'jasmine'),
  ('moroccan jasmine absolute', 'jasmine'),
  ('calabrian jasmine', 'jasmine'),
  ('indian jasminum grandiflorum', 'jasmine'),
  ('egyptian jasminum grandiflorum absolute', 'jasmine'),
  ('calabrian jasminum grandiflorum', 'jasmine'),
  ('night-blooming jasmine absolute', 'jasmine'),
  ('indonesian jasmine', 'jasmine'),
  ('turkish jasmine', 'jasmine'),
  ('indian jasminum grandiflorum absolute', 'jasmine'),
  ('indian jasminum auriculatum', 'jasmine'),
  ('grasse jasmine absolute', 'jasmine'),
  ('chinese jasmine absolute', 'jasmine'),
  ('french jasmine absolute', 'jasmine'),
  ('jasmine attar', 'jasmine'),
  ('japanese jasmine', 'jasmine'),
  ('jasmine concrete', 'jasmine'),
  ('jasmine sambac absolute', 'jasmine-sambac'),
  ('indian jasmine sambac', 'jasmine-sambac'),
  ('indian jasmine sambac absolute', 'jasmine-sambac'),
  ('egyptian jasmine sambac', 'jasmine-sambac'),
  ('chinese jasmine sambac', 'jasmine-sambac'),
  ('chinese jasmine sambac absolute', 'jasmine-sambac'),
  ('jonquil absolute', 'jonquil'),
  ('juniper berry', 'juniper'),
  ('himalayan juniper', 'juniper'),
  ('bulgarian juniper', 'juniper'),
  ('juniper berry co2', 'juniper'),
  ('italian juniper', 'juniper'),
  ('italian kelp', 'kelp'),
  ('french kelp absolute', 'kelp'),
  ('chinese kumquat', 'kumquat'),
  ('labdanum absolute', 'labdanum'),
  ('spanish labdanum', 'labdanum'),
  ('french labdanum', 'labdanum'),
  ('portuguese labdanum absolute', 'labdanum'),
  ('spanish labdanum absolute', 'labdanum'),
  ('provençal lavender', 'lavender'),
  ('french lavender', 'lavender'),
  ('lavender absolute', 'lavender'),
  ('true lavender', 'lavender'),
  ('bulgarian lavender', 'lavender'),
  ('italian lavender', 'lavender'),
  ('wild lavender', 'lavender'),
  ('provençal lavender absolute', 'lavender'),
  ('french lavender absolute', 'lavender'),
  ('kashmiri lavender', 'lavender'),
  ('russian lavender', 'lavender'),
  ('lavender concrete', 'lavender'),
  ('leathery notes', 'leather'),
  ('russian leather', 'leather'),
  ('tuscan leather', 'leather'),
  ('italian leather', 'leather'),
  ('kashmiri leather', 'leather'),
  ('spanish leather', 'leather'),
  ('english leather', 'leather'),
  ('french leather', 'leather'),
  ('sicilian lemon', 'lemon'),
  ('italian lemon', 'lemon'),
  ('amalfi lemon', 'lemon'),
  ('calabrian lemon', 'lemon'),
  ('primofiore lemon', 'lemon'),
  ('spanish lemon', 'lemon'),
  ('argentinian lemon', 'lemon'),
  ('french lemon', 'lemon'),
  ('moroccan lemon', 'lemon'),
  ('caribbean lemon', 'lemon'),
  ('sicilian primofiore lemon', 'lemon'),
  ('corsican lemon', 'lemon'),
  ('african lemon', 'lemon'),
  ('tahitian lemon', 'lemon'),
  ('tuscan lemon', 'lemon'),
  ('italian primofiore lemon', 'lemon'),
  ('italian lemon blossom', 'lemon-blossom'),
  ('indian lemon grass', 'lemon-grass'),
  ('sicilian lemon leaf', 'lemon-leaf'),
  ('italian lemon petitgrain', 'lemon-petitgrain'),
  ('italian lemon zest', 'lemon-zest'),
  ('sicilian lemon zest', 'lemon-zest'),
  ('liatris spicata absolute', 'liatris-spicata'),
  ('liquorice', 'licorice'),
  ('glycyrrhiza glabra', 'licorice'),
  ('licorice absolute', 'licorice'),
  ('liquorice absolute', 'licorice'),
  ('english lilac', 'lilac'),
  ('lilac concrete', 'lilac'),
  ('lilac absolute', 'lilac'),
  ('oriental lily', 'lily'),
  ('kenyan lily', 'lily'),
  ('italian lily of the valley', 'lily-of-the-valley'),
  ('german lily of the valley', 'lily-of-the-valley'),
  ('japanese lily of the valley', 'lily-of-the-valley'),
  ('french lily-of-the-valley', 'lily-of-the-valley'),
  ('tuscan lily of the valley', 'lily-of-the-valley'),
  ('sicilian lime', 'lime'),
  ('italian lime', 'lime'),
  ('caribbean lime', 'lime'),
  ('french lime', 'lime'),
  ('brazilian lime', 'lime'),
  ('dried lime', 'lime'),
  ('african lime', 'lime'),
  ('spanish lime', 'lime'),
  ('calabrian lime', 'lime'),
  ('indonesian lime', 'lime'),
  ('australian lime', 'lime'),
  ('malayan lime', 'lime'),
  ('linden blossom co2', 'linden-blossom'),
  ('french linden blossom', 'linden-blossom'),
  ('linden blossom absolute', 'linden-blossom'),
  ('chinese litsea cubeba', 'litsea-cubeba'),
  ('lotus absolute', 'lotus'),
  ('thai lychee', 'lychee'),
  ('chinese magnolia', 'magnolia'),
  ('magnolia absolute', 'magnolia'),
  ('italian magnolia', 'magnolia'),
  ('caribbean magnolia', 'magnolia'),
  ('indian magnolia', 'magnolia'),
  ('tuscan magnolia', 'magnolia'),
  ('french magnolia', 'magnolia'),
  ('mexican magnolia', 'magnolia'),
  ('mahogany wood', 'mahogany'),
  ('african mahogany', 'mahogany'),
  ('tangerine', 'mandarin-orange'),
  ('italian mandarin orange', 'mandarin-orange'),
  ('green mandarin orange', 'mandarin-orange'),
  ('clementine', 'mandarin-orange'),
  ('sicilian mandarin orange', 'mandarin-orange'),
  ('red mandarin orange', 'mandarin-orange'),
  ('mandarin orange zest', 'mandarin-orange'),
  ('calabrian mandarin orange', 'mandarin-orange'),
  ('italian green mandarin orange', 'mandarin-orange'),
  ('madagascan mandarin orange', 'mandarin-orange'),
  ('brazilian green mandarin orange', 'mandarin-orange'),
  ('calabrian green mandarin orange', 'mandarin-orange'),
  ('brazilian mandarin orange', 'mandarin-orange'),
  ('spanish mandarin orange', 'mandarin-orange'),
  ('italian mandarin orange zest', 'mandarin-orange'),
  ('italian red mandarin orange', 'mandarin-orange'),
  ('sicilian tangerine', 'mandarin-orange'),
  ('moroccan tangerine', 'mandarin-orange'),
  ('corsican clementine', 'mandarin-orange'),
  ('portuguese mandarin', 'mandarin-orange'),
  ('sicilian clementine', 'mandarin-orange'),
  ('argentinian mandarin orange', 'mandarin-orange'),
  ('italian clementine', 'mandarin-orange'),
  ('brazilian tangerine', 'mandarin-orange'),
  ('sicilian green mandarin orange', 'mandarin-orange'),
  ('japanese mandarin orange', 'mandarin-orange'),
  ('indian mandarin orange', 'mandarin-orange'),
  ('indian clementine', 'mandarin-orange'),
  ('wild mandarin orange', 'mandarin-orange'),
  ('chinese mandarin orange', 'mandarin-orange'),
  ('cuban tangerine', 'mandarin-orange'),
  ('algerian clementine', 'mandarin-orange'),
  ('caribbean mandarin orange', 'mandarin-orange'),
  ('italian mandarin orange leaf', 'mandarin-orange-leaf'),
  ('thai mango', 'mango'),
  ('brazilian mango', 'mango'),
  ('pot marigold', 'marigold'),
  ('african marigold', 'marigold'),
  ('madagascan marigold', 'marigold'),
  ('egyptian marigold', 'marigold'),
  ('mastic absolute', 'mastic'),
  ('moroccan mastic', 'mastic'),
  ('greek mastic', 'mastic'),
  ('peruvian mastic', 'mastic'),
  ('maté absolute', 'mate'),
  ('paraguayan maté absolute', 'mate'),
  ('brazilian maté', 'mate'),
  ('argentinian maté', 'mate'),
  ('rosa centifolia', 'may-rose'),
  ('rosa centifolia absolute', 'may-rose'),
  ('may rose absolute', 'may-rose'),
  ('french rosa centifolia', 'may-rose'),
  ('italian rosa centifolia', 'may-rose'),
  ('indian rosa centifolia', 'may-rose'),
  ('egyptian rosa centifolia', 'may-rose'),
  ('moroccan rosa centifolia', 'may-rose'),
  ('moroccan rosa centifolia absolute', 'may-rose'),
  ('persian melon', 'melon'),
  ('mimosa absolute', 'mimosa'),
  ('french mimosa', 'mimosa'),
  ('moroccan mimosa absolute', 'mimosa'),
  ('moroccan mimosa', 'mimosa'),
  ('grasse mimosa absolute', 'mimosa'),
  ('indian mimosa absolute', 'mimosa'),
  ('egyptian mimosa', 'mimosa'),
  ('mineral notes', 'mineral'),
  ('moroccan mint', 'mint'),
  ('italian mint', 'mint'),
  ('mexican mint', 'mint'),
  ('brazilian mint', 'mint'),
  ('french mint', 'mint'),
  ('egyptian mint', 'mint'),
  ('moroccan mugwort', 'mugwort'),
  ('kashmiri musk', 'musk'),
  ('tonkin musk', 'musk'),
  ('tibetan musk', 'musk'),
  ('siberian musk', 'musk'),
  ('persian musk', 'musk'),
  ('egyptian musk', 'musk'),
  ('himalayan musk', 'musk'),
  ('arabian musk', 'musk'),
  ('chinese musk', 'musk'),
  ('vietnamese musk', 'musk'),
  ('omani musk', 'musk'),
  ('italian musk', 'musk'),
  ('japanese musk', 'musk'),
  ('ethiopian myrrh', 'myrrh'),
  ('indian myrrh', 'myrrh'),
  ('arabian myrrh', 'myrrh'),
  ('myrrh absolute', 'myrrh'),
  ('chinese myrrh', 'myrrh'),
  ('african myrrh', 'myrrh'),
  ('egyptian myrrh', 'myrrh'),
  ('omani myrrh', 'myrrh'),
  ('italian myrtle', 'myrtle'),
  ('tunisian myrtle', 'myrtle'),
  ('narcissus absolute', 'narcissus'),
  ('french narcissus absolute', 'narcissus'),
  ('french narcissus', 'narcissus'),
  ('spanish narcissus', 'narcissus'),
  ('portuguese narcissus', 'narcissus'),
  ('tunisian neroli', 'neroli'),
  ('moroccan neroli', 'neroli'),
  ('italian neroli', 'neroli'),
  ('neroli absolute', 'neroli'),
  ('sicilian neroli', 'neroli'),
  ('french neroli', 'neroli'),
  ('egyptian neroli', 'neroli'),
  ('calabrian neroli', 'neroli'),
  ('paraguayan neroli', 'neroli'),
  ('spanish neroli', 'neroli'),
  ('african neroli', 'neroli'),
  ('indonesian nutmeg', 'nutmeg'),
  ('indian nutmeg', 'nutmeg'),
  ('spanish nutmeg', 'nutmeg'),
  ('brazilian nutmeg', 'nutmeg'),
  ('italian nutmeg', 'nutmeg'),
  ('sumatra nutmeg', 'nutmeg'),
  ('caribbean nutmeg', 'nutmeg'),
  ('nutmeg absolute', 'nutmeg'),
  ('madagascan nutmeg', 'nutmeg'),
  ('oak wood', 'oak'),
  ('oak wood absolute', 'oak'),
  ('oak wood co2', 'oak'),
  ('french oak', 'oak'),
  ('french oak wood', 'oak'),
  ('english oak wood', 'oak'),
  ('italian oak', 'oak'),
  ('oak co2', 'oak'),
  ('oak absolute', 'oak'),
  ('english oak', 'oak'),
  ('moss', 'oakmoss'),
  ('mossy notes', 'oakmoss'),
  ('irish moss', 'oakmoss'),
  ('oakmoss absolute', 'oakmoss'),
  ('italian oakmoss', 'oakmoss'),
  ('moroccan oakmoss', 'oakmoss'),
  ('spanish moss', 'oakmoss'),
  ('indian oakmoss', 'oakmoss'),
  ('moss absolute', 'oakmoss'),
  ('french oakmoss', 'oakmoss'),
  ('opoponax absolute', 'opoponax'),
  ('greek opoponax', 'opoponax'),
  ('sudanese opoponax', 'opoponax'),
  ('brazilian orange', 'orange'),
  ('orange zest', 'orange'),
  ('sicilian orange', 'orange'),
  ('italian orange', 'orange'),
  ('orange absolute', 'orange'),
  ('mexican orange', 'orange'),
  ('tunisian orange', 'orange'),
  ('spanish orange', 'orange'),
  ('chinese orange', 'orange'),
  ('calabrian orange', 'orange'),
  ('moroccan orange', 'orange'),
  ('wild orange', 'orange'),
  ('indian orange', 'orange'),
  ('italian orange zest', 'orange'),
  ('cuban orange', 'orange'),
  ('japanese orange', 'orange'),
  ('orange blossom absolute', 'orange-blossom'),
  ('african orange blossom', 'orange-blossom'),
  ('tunisian orange blossom', 'orange-blossom'),
  ('morrocan orange blossom', 'orange-blossom'),
  ('tunisian orange blossom absolute', 'orange-blossom'),
  ('moroccan orange blossom absolute', 'orange-blossom'),
  ('french orange blossom', 'orange-blossom'),
  ('egyptian orange blossom', 'orange-blossom'),
  ('sicilian orange blossom', 'orange-blossom'),
  ('spanish orange blossom absolute', 'orange-blossom'),
  ('egyptian orange blossom absolute', 'orange-blossom'),
  ('italian orange blossom', 'orange-blossom'),
  ('grasse orange blossom', 'orange-blossom'),
  ('spanish orange blossom', 'orange-blossom'),
  ('orange blossom concrete', 'orange-blossom'),
  ('african orange blossom absolute', 'orange-blossom'),
  ('italian orange blossom absolute', 'orange-blossom'),
  ('french orange blossom absolute', 'orange-blossom'),
  ('orange blossom water absolute', 'orange-blossom-water'),
  ('italian orange blossom water', 'orange-blossom-water'),
  ('tunisian orange blossom water absolute', 'orange-blossom-water'),
  ('wild orchid', 'orchid'),
  ('brazilian orchid', 'orchid'),
  ('spanish oregano', 'oregano'),
  ('osmanthus absolute', 'osmanthus'),
  ('chinese osmanthus', 'osmanthus'),
  ('chinese osmanthus absolute', 'osmanthus'),
  ('japanese osmanthus', 'osmanthus'),
  ('japanese osmanthus absolute', 'osmanthus'),
  ('himalayan osmanthus', 'osmanthus'),
  ('tibetan osmanthus', 'osmanthus'),
  ('italian osmanthus', 'osmanthus'),
  ('sumatra osmanthus', 'osmanthus'),
  ('indian oud', 'oud'),
  ('cambodian oud', 'oud'),
  ('laotian oud', 'oud'),
  ('thai oud', 'oud'),
  ('indonesian oud', 'oud'),
  ('borneo oud', 'oud'),
  ('assam oud', 'oud'),
  ('malayan oud', 'oud'),
  ('chinese oud', 'oud'),
  ('burmese oud', 'oud'),
  ('vietnamese oud', 'oud'),
  ('papua oud', 'oud'),
  ('nepalese oud', 'oud'),
  ('sumatra oud', 'oud'),
  ('arabian oud', 'oud'),
  ('persian oud', 'oud'),
  ('ozone', 'ozonic'),
  ('ozonic notes', 'ozonic'),
  ('brazilian palmarosa', 'palmarosa'),
  ('brazilian palo santo', 'palo-santo'),
  ('egyptian papyrus', 'papyrus'),
  ('indian papyrus', 'papyrus'),
  ('papyrus absolute', 'papyrus'),
  ('australian passion flower', 'passion-flower'),
  ('mexican passion flower', 'passion-flower'),
  ('brazilian passion fruit', 'passion-fruit'),
  ('peruvian passion fruit', 'passion-fruit'),
  ('indonesian patchouli', 'patchouli'),
  ('indian patchouli', 'patchouli'),
  ('singapore patchouli', 'patchouli'),
  ('malayan patchouli', 'patchouli'),
  ('sumatra patchouli', 'patchouli'),
  ('patchouli absolute', 'patchouli'),
  ('patchouli co2', 'patchouli'),
  ('balinese patchouli', 'patchouli'),
  ('madagascan patchouli', 'patchouli'),
  ('white peach', 'peach'),
  ('wild peach', 'peach'),
  ('italian peach', 'peach'),
  ('corsican peach', 'peach'),
  ('chinese white peach', 'peach'),
  ('peach blossom absolute', 'peach-blossom'),
  ('italian pear', 'pear'),
  ('african pear', 'pear'),
  ('english pear', 'pear'),
  ('chinese peony', 'peony'),
  ('aged pepper', 'pepper'),
  ('madagascan pepper', 'pepper'),
  ('madagascar pepper', 'pepper'),
  ('indian pepper', 'pepper'),
  ('nepalese pepper', 'pepper'),
  ('brazilian peppermint', 'peppermint'),
  ('peru balsam absolute', 'peru-balsam'),
  ('paraguayan petigrain', 'petitgrain'),
  ('italian petitgrain', 'petitgrain'),
  ('tunisian petitgrain', 'petitgrain'),
  ('sicilian petitgrain', 'petitgrain'),
  ('moroccan petitgrain', 'petitgrain'),
  ('petitgrain absolute', 'petitgrain'),
  ('indonesian pimento', 'pimento'),
  ('caribbean pimento', 'pimento'),
  ('russian pine', 'pine'),
  ('canadian pine', 'pine'),
  ('pine absolute', 'pine'),
  ('siberian pine absolute', 'pine'),
  ('french pine', 'pine'),
  ('pine needle absolute', 'pine-needle'),
  ('brazilian pineapple', 'pineapple'),
  ('african pineapple', 'pineapple'),
  ('pink lotus absolute', 'pink-lotus'),
  ('pink pepper co2', 'pink-pepper'),
  ('madagascan pink pepper', 'pink-pepper'),
  ('peruvian pink pepper', 'pink-pepper'),
  ('kenyan pink pepper', 'pink-pepper'),
  ('chinese pink pepper', 'pink-pepper'),
  ('french pink pepper', 'pink-pepper'),
  ('brazilian pink pepper', 'pink-pepper'),
  ('indian pink pepper', 'pink-pepper'),
  ('mirabelle plum', 'plum'),
  ('chinese plum', 'plum'),
  ('italian plum', 'plum'),
  ('himalaya poppy', 'poppy'),
  ('turkish poppy', 'poppy'),
  ('rain accord', 'rain'),
  ('italian raspberry', 'raspberry'),
  ('raspberry absolute', 'raspberry'),
  ('russian raspberry', 'raspberry'),
  ('raspberry leaf absolute', 'raspberry-leaf'),
  ('laotian red ginger', 'red-ginger'),
  ('spanish red thyme', 'red-thyme'),
  ('oriental resins', 'resins'),
  ('chinese rhubarb', 'rhubarb'),
  ('wild rhubarb', 'rhubarb'),
  ('roasted tonka bean absolute', 'roasted-tonka-bean'),
  ('bulgarian rose', 'rose'),
  ('turkish rose', 'rose'),
  ('damask rose', 'rose'),
  ('rose absolute', 'rose'),
  ('taif rose', 'rose'),
  ('turkish rose absolute', 'rose'),
  ('moroccan rose', 'rose'),
  ('rose water', 'rose'),
  ('wild rose', 'rose'),
  ('red rose', 'rose'),
  ('bulgarian rose absolute', 'rose'),
  ('rosebud', 'rose'),
  ('damask rose absolute', 'rose'),
  ('grasse rose', 'rose'),
  ('rose otto', 'rose'),
  ('moroccan rose absolute', 'rose'),
  ('indian rose', 'rose'),
  ('gallic rose', 'rose'),
  ('bulgarian rose otto', 'rose'),
  ('turkish damask rose', 'rose'),
  ('oriental rose', 'rose'),
  ('egyptian rose', 'rose'),
  ('persian rose', 'rose'),
  ('bulgarian damask rose', 'rose'),
  ('grasse rose absolute', 'rose'),
  ('himalayan rose', 'rose'),
  ('english rose', 'rose'),
  ('persian rose otto', 'rose'),
  ('turkish damask rose absolute', 'rose'),
  ('turkish rose otto', 'rose'),
  ('rose attar', 'rose'),
  ('rose oil', 'rose'),
  ('italian rose', 'rose'),
  ('chinese rose', 'rose'),
  ('indian damask rose', 'rose'),
  ('arabian rose', 'rose'),
  ('japanese rose', 'rose'),
  ('bulgarian damask rose absolute', 'rose'),
  ('indian rose absolute', 'rose'),
  ('taif rose otto', 'rose'),
  ('turkish rose otto absolute', 'rose'),
  ('moroccan damask rose', 'rose'),
  ('turkish rose concrete', 'rose'),
  ('chinese rose otto', 'rose'),
  ('egyptian rose absolute', 'rose'),
  ('caribbean rose', 'rose'),
  ('georgian rose', 'rose'),
  ('turkish rose water', 'rose'),
  ('taif rose absolute', 'rose'),
  ('tunisian rose', 'rose'),
  ('gallic rose absolute', 'rose'),
  ('georgian rose otto', 'rose'),
  ('bulgarian rose water', 'rose'),
  ('tunisian rose absolute', 'rose'),
  ('russian rose otto', 'rose'),
  ('wild rose absolute', 'rose'),
  ('damask rose water', 'rose'),
  ('damask rosebud', 'rose'),
  ('nepalese rose', 'rose'),
  ('russian rose', 'rose'),
  ('japanese rose otto', 'rose'),
  ('moroccan rosemary', 'rosemary'),
  ('italian rosemary', 'rosemary'),
  ('tunisian rosemary', 'rosemary'),
  ('spanish rosemary', 'rosemary'),
  ('rosemary absolute', 'rosemary'),
  ('brazilian rosewood', 'rosewood'),
  ('italian rosewood', 'rosewood'),
  ('indian rosewood', 'rosewood'),
  ('rum absolute', 'rum'),
  ('caribbean rum', 'rum'),
  ('cuban rum', 'rum'),
  ('paraguayan rum', 'rum'),
  ('rum co2', 'rum'),
  ('persian saffron', 'saffron'),
  ('italian saffron', 'saffron'),
  ('saffron absolute', 'saffron'),
  ('spanish saffron', 'saffron'),
  ('greek saffron', 'saffron'),
  ('kashmiri saffron', 'saffron'),
  ('saffron attar', 'saffron'),
  ('syrian saffron', 'saffron'),
  ('moroccan saffron', 'saffron'),
  ('japanese saffron absolute', 'saffron'),
  ('indonesian saffron', 'saffron'),
  ('french sage', 'sage'),
  ('sage absolute', 'sage'),
  ('wild sage', 'sage'),
  ('russian sage', 'sage'),
  ('italian sage', 'sage'),
  ('mysore sandalwood', 'sandalwood'),
  ('australian sandalwood', 'sandalwood'),
  ('indian sandalwood', 'sandalwood'),
  ('indonesian sandalwood', 'sandalwood'),
  ('ceylonese sandalwood', 'sandalwood'),
  ('papua sandalwood', 'sandalwood'),
  ('indian mysore sandalwood', 'sandalwood'),
  ('sandalwood absolute', 'sandalwood'),
  ('sandalwood co2', 'sandalwood'),
  ('african sandalwood', 'sandalwood'),
  ('madagascan sandalwood', 'sandalwood'),
  ('arabian sandalwood', 'sandalwood'),
  ('nepalese sandalwood', 'sandalwood'),
  ('caribbean sandalwood', 'sandalwood'),
  ('kashmiri sandalwood', 'sandalwood'),
  ('indian sandalwood co2', 'sandalwood'),
  ('mysore sandalwood absolute', 'sandalwood'),
  ('haitian sandalwood', 'sandalwood'),
  ('salt', 'sea-salt'),
  ('italian sea salt', 'sea-salt'),
  ('himalayan salt', 'sea-salt'),
  ('seagrass absolute', 'seagrass'),
  ('sensual skin accord', 'sensual-skin'),
  ('sesame absolute', 'sesame'),
  ('indian sesame', 'sesame'),
  ('japanese shiso', 'shiso'),
  ('nepalese sichuan pepper', 'sichuan-pepper'),
  ('nepalese sichuan pepper co2', 'sichuan-pepper'),
  ('sichuan pepper absolute', 'sichuan-pepper'),
  ('oriental spices', 'spices'),
  ('indian spices', 'spices'),
  ('arabian spices', 'spices'),
  ('cambodian spices', 'spices'),
  ('vietnamese spices', 'spices'),
  ('vietnamese star anise', 'star-anise'),
  ('french star jasmine', 'star-jasmine'),
  ('siberian stone pine', 'stone-pine'),
  ('swiss stone pine', 'stone-pine'),
  ('woodland strawberry', 'strawberry'),
  ('italian strawberry', 'strawberry'),
  ('french strawberry', 'strawberry'),
  ('italian woodland strawberry', 'strawberry'),
  ('italian suede', 'suede'),
  ('cuban sugar cane', 'sugar-cane'),
  ('caribbean sugar cane', 'sugar-cane'),
  ('french sunflower', 'sunflower'),
  ('sweet acacia absolute', 'sweet-acacia'),
  ('chinese tagetes', 'tagetes'),
  ('ceylon tea', 'tea'),
  ('tea absolute', 'tea'),
  ('assam tea', 'tea'),
  ('japanese tea', 'tea'),
  ('indian tea', 'tea'),
  ('himalayan tea', 'tea'),
  ('tea rose absolute', 'tea-rose'),
  ('teakwood', 'teak'),
  ('indonesian teakwood', 'teak'),
  ('wild thyme', 'thyme'),
  ('thyme absolute', 'thyme'),
  ('greek thyme', 'thyme'),
  ('tiaré absolute', 'tiare'),
  ('tobacco absolute', 'tobacco'),
  ('tobacco leaf', 'tobacco'),
  ('cuban tobacco', 'tobacco'),
  ('turkish tobacco', 'tobacco'),
  ('tuscan tobacco', 'tobacco'),
  ('brazilian tobacco', 'tobacco'),
  ('turkish tobacco absolute', 'tobacco'),
  ('french tobacco', 'tobacco'),
  ('paraguayan tobacco', 'tobacco'),
  ('indonesian tobacco', 'tobacco'),
  ('tolu balm', 'tolu-balsam'),
  ('colombian tolu balm', 'tolu-balsam'),
  ('tolu balm absolute', 'tolu-balsam'),
  ('peruvian tolu balm', 'tolu-balsam'),
  ('tonka bean absolute', 'tonka-bean'),
  ('venezuelan tonka bean', 'tonka-bean'),
  ('brazilian tonka bean', 'tonka-bean'),
  ('venezuelan tonka bean absolute', 'tonka-bean'),
  ('brazilian tonka bean absolute', 'tonka-bean'),
  ('caribbean tonka bean', 'tonka-bean'),
  ('madagascan tonka bean', 'tonka-bean'),
  ('colombian tonka bean', 'tonka-bean'),
  ('indian tonka bean absolute', 'tonka-bean'),
  ('mexican tonka bean', 'tonka-bean'),
  ('tree moss', 'treemoss'),
  ('tree moss absolute', 'treemoss'),
  ('tuberose absolute', 'tuberose'),
  ('indian tuberose', 'tuberose'),
  ('indian tuberose absolute', 'tuberose'),
  ('mexican tuberose', 'tuberose'),
  ('egyptian tuberose', 'tuberose'),
  ('grasse tuberose', 'tuberose'),
  ('french tuberose', 'tuberose'),
  ('grasse tuberose absolute', 'tuberose'),
  ('mexican tuberose absolute', 'tuberose'),
  ('french tulip', 'tulip'),
  ('turmeric absolute', 'turmeric'),
  ('bourbon vanilla', 'vanilla'),
  ('vanilla absolute', 'vanilla'),
  ('vanilla orchid', 'vanilla'),
  ('bourbon vanilla absolute', 'vanilla'),
  ('vanilla blossom', 'vanilla'),
  ('tahitian vanilla', 'vanilla'),
  ('french vanilla', 'vanilla'),
  ('mexican vanilla', 'vanilla'),
  ('vanilla co2', 'vanilla'),
  ('madagascan vanilla blossom', 'vanilla'),
  ('tahitian vanilla absolute', 'vanilla'),
  ('bourbon vanilla co2', 'vanilla'),
  ('tahitian vanilla blossom', 'vanilla'),
  ('zanzibar vanilla', 'vanilla'),
  ('madagascan vanilla orchid absolute', 'vanilla'),
  ('haitian vanilla', 'vanilla'),
  ('african vanilla', 'vanilla'),
  ('indonesian vanilla', 'vanilla'),
  ('haitian vanilla orchid', 'vanilla'),
  ('tahitian vanilla orchid', 'vanilla'),
  ('indian bourbon vanilla', 'vanilla'),
  ('brazilian vanilla', 'vanilla'),
  ('madagascar vanilla orchid', 'vanilla'),
  ('mexican vanilla absolute', 'vanilla'),
  ('indian vanilla', 'vanilla'),
  ('vanilla absolute co2', 'vanilla'),
  ('tahitian vanilla co2', 'vanilla'),
  ('vervain', 'verbena'),
  ('lemon vervain', 'verbena'),
  ('verbena absolute', 'verbena'),
  ('vervain co2', 'verbena'),
  ('indian verbena', 'verbena'),
  ('haitian vetiver', 'vetiver'),
  ('java vetiver', 'vetiver'),
  ('bourbon vetiver', 'vetiver'),
  ('madagascan vetiver', 'vetiver'),
  ('tahitian vetiver', 'vetiver'),
  ('indian vetiver', 'vetiver'),
  ('brazilian vetiver', 'vetiver'),
  ('vetiver absolute', 'vetiver'),
  ('vetiver co2', 'vetiver'),
  ('egyptian vetiver', 'vetiver'),
  ('wild vetiver', 'vetiver'),
  ('haitian vetiver absolute', 'vetiver'),
  ('african vetiver', 'vetiver'),
  ('sumatra vetiver', 'vetiver'),
  ('laotian vetiver', 'vetiver'),
  ('caribbean vetiver', 'vetiver'),
  ('himalayan vetiver', 'vetiver'),
  ('violet absolute', 'violet'),
  ('african violet', 'violet'),
  ('french violet', 'violet'),
  ('egyptian violet', 'violet'),
  ('italian violet', 'violet'),
  ('grasse violet', 'violet'),
  ('violet leaf absolute', 'violet-leaf'),
  ('egyptian violet leaf absolute', 'violet-leaf'),
  ('egyptian violet leaf', 'violet-leaf'),
  ('italian violet leaf', 'violet-leaf'),
  ('french violet leaf', 'violet-leaf'),
  ('grasse violet leaf', 'violet-leaf'),
  ('french violet leaf absolute', 'violet-leaf'),
  ('moroccan violet leaf', 'violet-leaf'),
  ('whisky co2', 'whisky'),
  ('irish white ambergris', 'white-ambergris'),
  ('white cedarwood', 'white-cedar'),
  ('chinese white cedar', 'white-cedar'),
  ('canadian white cedar', 'white-cedar'),
  ('tuscan white iris', 'white-iris'),
  ('egyptian white lotus', 'white-lotus'),
  ('thai white lotus', 'white-lotus'),
  ('indian white pepper absolute', 'white-pepper'),
  ('white pepper absolute', 'white-pepper'),
  ('white rose absolute', 'white-rose'),
  ('white rose otto', 'white-rose'),
  ('bulgarian white rose otto', 'white-rose'),
  ('indonesian white rose', 'white-rose'),
  ('chinese white tea', 'white-tea'),
  ('spanish white thyme', 'white-thyme'),
  ('japanese wisteria', 'wisteria'),
  ('artemisia', 'wormwood'),
  ('absinth', 'wormwood'),
  ('absinthe wormwood', 'wormwood'),
  ('moroccan artemisia', 'wormwood'),
  ('greek artemisia', 'wormwood'),
  ('moroccan wormwood', 'wormwood'),
  ('roman wormwood', 'wormwood'),
  ('madagascan ylang-ylang', 'ylang-ylang'),
  ('ylang-ylang absolute', 'ylang-ylang'),
  ('thai ylang-ylang', 'ylang-ylang'),
  ('indonesian ylang-ylang', 'ylang-ylang'),
  ('caribbean ylang-ylang', 'ylang-ylang'),
  ('madagascan ylang-ylang absolute', 'ylang-ylang'),
  ('tahitian ylang-ylang', 'ylang-ylang'),
  ('malayan ylang-ylang', 'ylang-ylang'),
  ('japanese yuzu', 'yuzu'),
  ('korean yuzu', 'yuzu'),
  ('absinthe', 'wormwood'),
  ('agarwood', 'oud'),
  ('aldehyde', 'aldehydes'),
  ('animalic', 'animalic-notes'),
  ('aoud', 'oud'),
  ('aromatic', 'aromatic-notes'),
  ('balsamic', 'balsamic-notes'),
  ('black currant', 'blackcurrant'),
  ('boswellia', 'frankincense'),
  ('cacao', 'cocoa'),
  ('cananga odorata', 'ylang-ylang'),
  ('cassis', 'blackcurrant'),
  ('cedar wood', 'cedarwood'),
  ('citrus aurantium', 'bitter-orange'),
  ('commiphora', 'myrrh'),
  ('creamy', 'creamy-notes'),
  ('fresh', 'fresh-notes'),
  ('gaiacwood', 'gaiac-wood'),
  ('green', 'green-notes'),
  ('guaiac wood', 'gaiac-wood'),
  ('guaiacwood', 'gaiac-wood'),
  ('isoesuper', 'iso-e-super'),
  ('jasminum sambac', 'jasmine-sambac'),
  ('labdanum resin', 'labdanum'),
  ('leathery', 'leather'),
  ('lily-of-the-valley', 'lily-of-the-valley'),
  ('mandarin', 'mandarin-orange'),
  ('marine', 'aquatic'),
  ('metallic', 'metallic-notes'),
  ('mossy', 'oakmoss'),
  ('muguet', 'lily-of-the-valley'),
  ('neroli oil', 'neroli'),
  ('olibanum', 'frankincense'),
  ('orris', 'iris'),
  ('oudh', 'oud'),
  ('petigrain', 'petitgrain'),
  ('petit grain', 'petitgrain'),
  ('powdery', 'powdery-notes'),
  ('provencal lavender', 'lavender'),
  ('sandal', 'sandalwood'),
  ('santal', 'sandalwood'),
  ('sea water', 'seawater'),
  ('storax', 'benzoin'),
  ('sweet', 'sweet-notes'),
  ('szechuan pepper', 'sichuan-pepper'),
  ('vanilla bean', 'vanilla'),
  ('vanille', 'vanilla'),
  ('woody', 'woody-notes'),
  ('ylang ylang', 'ylang-ylang')
) as v (alias, note_slug)
join notes n on n.slug = v.note_slug
on conflict (alias) do update set note_id = excluded.note_id;
